name: Xcode Test Practice
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Set Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app
    - name: Build and Test
      run: |
        xcodebuild test \
        -scheme SwiftUIPractice \
        -project ./SwiftUIPractice/SwiftUIPractice.xcodeproj \
        -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
