name: Xcode Version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Set Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app
    - name: Check Xcode version
      run: xcodebuild -version
